logging:
  level:
    com:
      cyperux: INFO
spring:
  application:
    name: cyperux
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/cyperux
    username: cyperux
  task:
    execution:
      pool:
        keep-alive: 10s
        max-size: 16
        queue-capacity: 100
      thread-name-prefix: cyperux-task-
    scheduling:
      pool:
        size: 2
      thread-name-prefix: cyperux-scheduling-
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
application:
  logging:
    logstash:
      tcp:
        enabled: false
        host: localhost
        port: 5000
        ring-buffer-size: 8192
        shutdown_grace_period: PT1M
